source "https://rubygems.org"

# Global gems
gem "rails", "8.0.2"
gem "propshaft"                           
gem "sprockets-rails"                     
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem "kamal", require: false
gem "thruster", require: false
gem "govuk_publishing_components"
gem "ruby-openai"gem "bootsnap", require: false
gem "dartsass-rails", "~> 0.5.1"

group :development, :test do
  gem "brakeman", require: false
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "rspec-rails"
  gem "rubocop-govuk", require: false
  gem "httparty"
end

group :development do
  gem "foreman"
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
